apiVersion: v1
kind: Service
metadata:
  name: nodejs-adonisjs
  namespace: nodejs-adonisjs
  labels:
    app: nodejs-adonisjs
spec:
  type: ClusterIP
  selector:
    app: nodejs-adonisjs
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
    name: http
